default_title: HR Manager
meta_keywords: "employee management, human resource management, simple, hr manager"
meta_description: "Advanced ruby on rails human resource manager, robust human resource management, human resource system, employee appraisal system"
